steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraformer-app:latest', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/terraformer-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - terraformer-app
      - --image
      - gcr.io/$PROJECT_ID/terraformer-app:latest
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/terraformer-app:latest'
